#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
#
# Constraint C1: every dependency must be OSI-licensed and nothing in the
# runtime path may require a commercial account.
#
# Emits a Markdown inventory of resolved licences for both services, from the
# lockfiles rather than from a hand-maintained list, so it cannot drift.
# Exits non-zero if any dependency reports no licence at all.

set -uo pipefail

cd "$(dirname "$0")/../.."

echo "# Dependency licence inventory"
echo
echo "Generated by \`make licenses\`. Do not edit by hand."
echo
echo "Constraint C1 requires every dependency to be OSI-licensed and forbids any"
echo "component that needs a commercial account. This file is the evidence."
echo

missing=0

# ---------------------------------------------------------------- PHP -------
echo "## PHP (composer)"
echo
echo "| Package | Version | Licence |"
echo "|---|---|---|"

if [[ -f api/composer.lock ]]; then
    php -r '
        $lock = json_decode(file_get_contents("api/composer.lock"), true);
        $rows = array_merge($lock["packages"] ?? [], $lock["packages-dev"] ?? []);
        usort($rows, fn($a, $b) => strcmp($a["name"], $b["name"]));
        foreach ($rows as $p) {
            $lic = empty($p["license"]) ? "UNKNOWN" : implode(" / ", $p["license"]);
            printf("| %s | %s | %s |\n", $p["name"], $p["version"], $lic);
        }
    '
    if php -r '
        $lock = json_decode(file_get_contents("api/composer.lock"), true);
        $rows = array_merge($lock["packages"] ?? [], $lock["packages-dev"] ?? []);
        foreach ($rows as $p) { if (empty($p["license"])) { exit(1); } }
        exit(0);
    '; then :; else missing=1; fi
else
    echo "| _composer.lock not found_ | | |"
fi

echo

# -------------------------------------------------------------- Python -----
echo "## Python (pip)"
echo
echo "| Package | Version | Licence |"
echo "|---|---|---|"

if [[ -x ml/.venv/bin/python ]]; then
    ml/.venv/bin/python - <<'PY'
import importlib.metadata as md

rows = []
for dist in md.distributions():
    name = dist.metadata["Name"]
    if not name:
        continue
    lic = dist.metadata.get("License-Expression") or dist.metadata.get("License") or ""
    if not lic or lic.strip() in {"UNKNOWN", ""}:
        classifiers = [
            c.rsplit("::", 1)[-1].strip()
            for c in dist.metadata.get_all("Classifier") or []
            if c.startswith("License ::")
        ]
        lic = " / ".join(classifiers) if classifiers else "UNKNOWN"
    lic = lic.splitlines()[0][:80]
    rows.append((name, dist.version, lic))

for name, version, lic in sorted(rows, key=lambda r: r[0].lower()):
    print(f"| {name} | {version} | {lic} |")
PY
else
    echo "| _ml/.venv not found; run make setup_ | | |"
fi

echo
echo "## Model weights"
echo
echo "| Model | Licence | Source |"
echo "|---|---|---|"
echo "| intfloat/multilingual-e5-base | MIT | Hugging Face, downloaded at image build time |"
echo
echo "## Map data"
echo
echo "| Asset | Licence |"
echo "|---|---|"
echo "| Location geometry (OpenStreetMap-derived GeoJSON) | ODbL 1.0 |"

if [[ $missing -eq 1 ]]; then
    echo
    echo "> **WARNING:** one or more packages report no licence. Investigate before release."
    exit 1
fi
